//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace imbNLP.PipelineDSLD
{
	internal static partial class Constants
	{
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string DesignerFileExtension = "imbNLPPipelineDSLD";
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string ProductName = @"NLPPipelineDSLD";
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string CompanyName = @"imbVeles";
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string ProductVersion = "1.0.0.0";

		// Menu definitions
		public static readonly global::System.ComponentModel.Design.CommandID NLPPipelineDSLDDiagramMenu = new global::System.ComponentModel.Design.CommandID(new global::System.Guid(NLPPipelineDSLDCommandSetId), 0x10000);
		public static readonly global::System.ComponentModel.Design.CommandID NLPPipelineDSLDExplorerMenu = new global::System.ComponentModel.Design.CommandID(new global::System.Guid(NLPPipelineDSLDCommandSetId), 0x10001);

		// Command definitions
		public static readonly global::System.ComponentModel.Design.CommandID ViewNLPPipelineDSLDExplorerCommand = new global::System.ComponentModel.Design.CommandID(new global::System.Guid(NLPPipelineDSLDCommandSetId), 0x0001);
	
		// Package identifier
		public const string NLPPipelineDSLDPackageId = "c66e3f54-5765-4ab9-a0f5-d773c4063e00";
		
		// Editor factory identifier
		public const string NLPPipelineDSLDEditorFactoryId = "e16bcfed-eb3d-41d0-bf57-743bed0804eb";
		
		public const string DefaultDiagramExtension = ".diagram";
		
		// Model explorer tool window identifier
		public const string NLPPipelineDSLDModelExplorerToolWindowId = "4f7870a6-1bed-41c1-9824-a9737fb32b29";
	}
}
//
// Constants not generated from values in DesignerDefinition.dsl are defined below
//
namespace imbNLP.PipelineDSLD
{
	internal static partial class Constants
	{
		// Menu identifier
		public const string NLPPipelineDSLDCommandSetId = "4d90c9c7-87f4-40a8-a16c-3ec468def513";
	}
}