//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using DslModeling = global::Microsoft.VisualStudio.Modeling;
using DslDesign = global::Microsoft.VisualStudio.Modeling.Design;
namespace imbNLP.PipelineDSLD
{
	/// <summary>
	/// DomainRelationship ExampleModelHasElements
	/// Embedding relationship between the Model and Elements
	/// </summary>
	[DslDesign::DisplayNameResource("imbNLP.PipelineDSLD.ExampleModelHasElements.DisplayName", typeof(global::imbNLP.PipelineDSLD.NLPPipelineDSLDDomainModel), "imbNLP.PipelineDSLD.GeneratedCode.DomainModelResx")]
	[DslDesign::DescriptionResource("imbNLP.PipelineDSLD.ExampleModelHasElements.Description", typeof(global::imbNLP.PipelineDSLD.NLPPipelineDSLDDomainModel), "imbNLP.PipelineDSLD.GeneratedCode.DomainModelResx")]
	[DslModeling::DomainModelOwner(typeof(global::imbNLP.PipelineDSLD.NLPPipelineDSLDDomainModel))]
	[global::System.CLSCompliant(true)]
	[DslModeling::DomainRelationship(IsEmbedding=true)]
	[DslModeling::DomainObjectId("460c1dca-b35f-4c8c-bf9d-90fdedaf4419")]
	public partial class ExampleModelHasElements : DslModeling::ElementLink
	{
		#region Constructors, domain class Id
		
		/// <summary>
		/// ExampleModelHasElements domain class Id.
		/// </summary>
		public static readonly new global::System.Guid DomainClassId = new global::System.Guid(0x460c1dca, 0xb35f, 0x4c8c, 0xbf, 0x9d, 0x90, 0xfd, 0xed, 0xaf, 0x44, 0x19);
	
				
		/// <summary>
		/// Constructor
		/// Creates a ExampleModelHasElements link in the same Partition as the given ExampleModel
		/// </summary>
		/// <param name="source">ExampleModel to use as the source of the relationship.</param>
		/// <param name="target">ExampleElement to use as the target of the relationship.</param>
		public ExampleModelHasElements(ExampleModel source, ExampleElement target)
			: base((source != null ? source.Partition : null), new DslModeling::RoleAssignment[]{new DslModeling::RoleAssignment(ExampleModelHasElements.ExampleModelDomainRoleId, source), new DslModeling::RoleAssignment(ExampleModelHasElements.ElementDomainRoleId, target)}, null)
		{
		}
		
		/// <summary>
		/// Constructor
		/// </summary>
		/// <param name="store">Store where new link is to be created.</param>
		/// <param name="roleAssignments">List of relationship role assignments.</param>
		public ExampleModelHasElements(DslModeling::Store store, params DslModeling::RoleAssignment[] roleAssignments)
			: base(store != null ? store.DefaultPartitionForClass(DomainClassId) : null, roleAssignments, null)
		{
		}
		
		/// <summary>
		/// Constructor
		/// </summary>
		/// <param name="store">Store where new link is to be created.</param>
		/// <param name="roleAssignments">List of relationship role assignments.</param>
		/// <param name="propertyAssignments">List of properties assignments to set on the new link.</param>
		public ExampleModelHasElements(DslModeling::Store store, DslModeling::RoleAssignment[] roleAssignments, DslModeling::PropertyAssignment[] propertyAssignments)
			: base(store != null ? store.DefaultPartitionForClass(DomainClassId) : null, roleAssignments, propertyAssignments)
		{
		}
		
		/// <summary>
		/// Constructor
		/// </summary>
		/// <param name="partition">Partition where new link is to be created.</param>
		/// <param name="roleAssignments">List of relationship role assignments.</param>
		public ExampleModelHasElements(DslModeling::Partition partition, params DslModeling::RoleAssignment[] roleAssignments)
			: base(partition, roleAssignments, null)
		{
		}
		
		/// <summary>
		/// Constructor
		/// </summary>
		/// <param name="partition">Partition where new link is to be created.</param>
		/// <param name="roleAssignments">List of relationship role assignments.</param>
		/// <param name="propertyAssignments">List of properties assignments to set on the new link.</param>
		public ExampleModelHasElements(DslModeling::Partition partition, DslModeling::RoleAssignment[] roleAssignments, DslModeling::PropertyAssignment[] propertyAssignments)
			: base(partition, roleAssignments, propertyAssignments)
		{
		}
		#endregion
		#region ExampleModel domain role code
		
		/// <summary>
		/// ExampleModel domain role Id.
		/// </summary>
		public static readonly global::System.Guid ExampleModelDomainRoleId = new global::System.Guid(0xb98e231f, 0x5f83, 0x4427, 0x91, 0x41, 0xfe, 0x8d, 0x9e, 0xfa, 0x45, 0x6b);
		
		/// <summary>
		/// DomainRole ExampleModel
		/// </summary>
		[DslDesign::DisplayNameResource("imbNLP.PipelineDSLD.ExampleModelHasElements/ExampleModel.DisplayName", typeof(global::imbNLP.PipelineDSLD.NLPPipelineDSLDDomainModel), "imbNLP.PipelineDSLD.GeneratedCode.DomainModelResx")]
		[DslDesign::DescriptionResource("imbNLP.PipelineDSLD.ExampleModelHasElements/ExampleModel.Description", typeof(global::imbNLP.PipelineDSLD.NLPPipelineDSLDDomainModel), "imbNLP.PipelineDSLD.GeneratedCode.DomainModelResx")]
		[DslModeling::DomainRole(DslModeling::DomainRoleOrder.Source, PropertyName = "Elements", PropertyDisplayNameKey="imbNLP.PipelineDSLD.ExampleModelHasElements/ExampleModel.PropertyDisplayName",  PropagatesCopy = DslModeling::PropagatesCopyOption.PropagatesCopyToLinkAndOppositeRolePlayer, Multiplicity = DslModeling::Multiplicity.ZeroMany)]
		[DslModeling::DomainObjectId("b98e231f-5f83-4427-9141-fe8d9efa456b")]
		public virtual ExampleModel ExampleModel
		{
			[global::System.Diagnostics.DebuggerStepThrough]
			get
			{
				return (ExampleModel)DslModeling::DomainRoleInfo.GetRolePlayer(this, ExampleModelDomainRoleId);
			}
			[global::System.Diagnostics.DebuggerStepThrough]
			set
			{
				DslModeling::DomainRoleInfo.SetRolePlayer(this, ExampleModelDomainRoleId, value);
			}
		}
				
		#endregion
		#region Static methods to access ExampleModel of a ExampleElement
		/// <summary>
		/// Gets ExampleModel.
		/// </summary>
		[global::System.Diagnostics.DebuggerStepThrough]
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011")]
		public static ExampleModel GetExampleModel(ExampleElement element)
		{
			return DslModeling::DomainRoleInfo.GetLinkedElement(element, ElementDomainRoleId) as ExampleModel;
		}
		
		/// <summary>
		/// Sets ExampleModel.
		/// </summary>
		[global::System.Diagnostics.DebuggerStepThrough]
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011")]
		public static void SetExampleModel(ExampleElement element, ExampleModel newExampleModel)
		{
			DslModeling::DomainRoleInfo.SetLinkedElement(element, ElementDomainRoleId, newExampleModel);
		}
		#endregion
		#region Element domain role code
		
		/// <summary>
		/// Element domain role Id.
		/// </summary>
		public static readonly global::System.Guid ElementDomainRoleId = new global::System.Guid(0x405af471, 0x9d61, 0x4b00, 0x93, 0x61, 0xb1, 0x7f, 0x3d, 0x56, 0xba, 0x16);
		
		/// <summary>
		/// DomainRole Element
		/// </summary>
		[DslDesign::DisplayNameResource("imbNLP.PipelineDSLD.ExampleModelHasElements/Element.DisplayName", typeof(global::imbNLP.PipelineDSLD.NLPPipelineDSLDDomainModel), "imbNLP.PipelineDSLD.GeneratedCode.DomainModelResx")]
		[DslDesign::DescriptionResource("imbNLP.PipelineDSLD.ExampleModelHasElements/Element.Description", typeof(global::imbNLP.PipelineDSLD.NLPPipelineDSLDDomainModel), "imbNLP.PipelineDSLD.GeneratedCode.DomainModelResx")]
		[DslModeling::DomainRole(DslModeling::DomainRoleOrder.Target, PropertyName = "ExampleModel", PropertyDisplayNameKey="imbNLP.PipelineDSLD.ExampleModelHasElements/Element.PropertyDisplayName", PropagatesDelete = true,  PropagatesCopy = DslModeling::PropagatesCopyOption.DoNotPropagateCopy, Multiplicity = DslModeling::Multiplicity.One)]
		[DslModeling::DomainObjectId("405af471-9d61-4b00-9361-b17f3d56ba16")]
		public virtual ExampleElement Element
		{
			[global::System.Diagnostics.DebuggerStepThrough]
			get
			{
				return (ExampleElement)DslModeling::DomainRoleInfo.GetRolePlayer(this, ElementDomainRoleId);
			}
			[global::System.Diagnostics.DebuggerStepThrough]
			set
			{
				DslModeling::DomainRoleInfo.SetRolePlayer(this, ElementDomainRoleId, value);
			}
		}
				
		#endregion
		#region Static methods to access Elements of a ExampleModel
		/// <summary>
		/// Gets a list of Elements.
		/// </summary>
		[global::System.Diagnostics.DebuggerStepThrough]
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011")]
		public static DslModeling::LinkedElementCollection<ExampleElement> GetElements(ExampleModel element)
		{
			return GetRoleCollection<DslModeling::LinkedElementCollection<ExampleElement>, ExampleElement>(element, ExampleModelDomainRoleId);
		}
		#endregion
		#region ExampleModel link accessor
		/// <summary>
		/// Get the list of ExampleModelHasElements links to a ExampleModel.
		/// </summary>
		[global::System.Diagnostics.DebuggerStepThrough]
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011")]
		public static global::System.Collections.ObjectModel.ReadOnlyCollection<global::imbNLP.PipelineDSLD.ExampleModelHasElements> GetLinksToElements ( global::imbNLP.PipelineDSLD.ExampleModel exampleModelInstance )
		{
			return DslModeling::DomainRoleInfo.GetElementLinks<global::imbNLP.PipelineDSLD.ExampleModelHasElements>(exampleModelInstance, global::imbNLP.PipelineDSLD.ExampleModelHasElements.ExampleModelDomainRoleId);
		}
		#endregion
		#region Element link accessor
		/// <summary>
		/// Get the ExampleModelHasElements link to a ExampleElement.
		/// </summary>
		[global::System.Diagnostics.DebuggerStepThrough]
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011")]
		public static global::imbNLP.PipelineDSLD.ExampleModelHasElements GetLinkToExampleModel (global::imbNLP.PipelineDSLD.ExampleElement elementInstance)
		{
			global::System.Collections.Generic.IList<global::imbNLP.PipelineDSLD.ExampleModelHasElements> links = DslModeling::DomainRoleInfo.GetElementLinks<global::imbNLP.PipelineDSLD.ExampleModelHasElements>(elementInstance, global::imbNLP.PipelineDSLD.ExampleModelHasElements.ElementDomainRoleId);
			global::System.Diagnostics.Debug.Assert(links.Count <= 1, "Multiplicity of Element not obeyed.");
			if ( links.Count == 0 )
			{
				return null;
			}
			else
			{
				return links[0];
			}
		}
		#endregion
		#region ExampleModelHasElements instance accessors
		
		/// <summary>
		/// Get any ExampleModelHasElements links between a given ExampleModel and a ExampleElement.
		/// </summary>
		[global::System.Diagnostics.DebuggerStepThrough]
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011")]
		public static global::System.Collections.ObjectModel.ReadOnlyCollection<global::imbNLP.PipelineDSLD.ExampleModelHasElements> GetLinks( global::imbNLP.PipelineDSLD.ExampleModel source, global::imbNLP.PipelineDSLD.ExampleElement target )
		{
			global::System.Collections.Generic.List<global::imbNLP.PipelineDSLD.ExampleModelHasElements> outLinks = new global::System.Collections.Generic.List<global::imbNLP.PipelineDSLD.ExampleModelHasElements>();
			global::System.Collections.Generic.IList<global::imbNLP.PipelineDSLD.ExampleModelHasElements> links = DslModeling::DomainRoleInfo.GetElementLinks<global::imbNLP.PipelineDSLD.ExampleModelHasElements>(source, global::imbNLP.PipelineDSLD.ExampleModelHasElements.ExampleModelDomainRoleId);
			foreach ( global::imbNLP.PipelineDSLD.ExampleModelHasElements link in links )
			{
				if ( target.Equals(link.Element) )
				{
					outLinks.Add(link);
				}
			}
			return outLinks.AsReadOnly();
		}
		/// <summary>
		/// Get the one ExampleModelHasElements link between a given ExampleModeland a ExampleElement.
		/// </summary>
		[global::System.Diagnostics.DebuggerStepThrough]
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011")]
		public static global::imbNLP.PipelineDSLD.ExampleModelHasElements GetLink( global::imbNLP.PipelineDSLD.ExampleModel source, global::imbNLP.PipelineDSLD.ExampleElement target )
		{
			global::System.Collections.Generic.IList<global::imbNLP.PipelineDSLD.ExampleModelHasElements> links = DslModeling::DomainRoleInfo.GetElementLinks<global::imbNLP.PipelineDSLD.ExampleModelHasElements>(source, global::imbNLP.PipelineDSLD.ExampleModelHasElements.ExampleModelDomainRoleId);
			foreach ( global::imbNLP.PipelineDSLD.ExampleModelHasElements link in links )
			{
				if ( target.Equals(link.Element) )
				{
					return link;
				}
			}
			return null;
		}
		
		#endregion
	}
}
namespace imbNLP.PipelineDSLD
{
	/// <summary>
	/// DomainRelationship ExampleElementReferencesTargets
	/// Reference relationship between Elements.
	/// </summary>
	[DslDesign::DisplayNameResource("imbNLP.PipelineDSLD.ExampleElementReferencesTargets.DisplayName", typeof(global::imbNLP.PipelineDSLD.NLPPipelineDSLDDomainModel), "imbNLP.PipelineDSLD.GeneratedCode.DomainModelResx")]
	[DslDesign::DescriptionResource("imbNLP.PipelineDSLD.ExampleElementReferencesTargets.Description", typeof(global::imbNLP.PipelineDSLD.NLPPipelineDSLDDomainModel), "imbNLP.PipelineDSLD.GeneratedCode.DomainModelResx")]
	[DslModeling::DomainModelOwner(typeof(global::imbNLP.PipelineDSLD.NLPPipelineDSLDDomainModel))]
	[global::System.CLSCompliant(true)]
	[DslModeling::DomainRelationship()]
	[DslModeling::DomainObjectId("a7cdcbb0-161b-4135-9dbb-5bbd4bbde37c")]
	public partial class ExampleElementReferencesTargets : DslModeling::ElementLink
	{
		#region Constructors, domain class Id
		
		/// <summary>
		/// ExampleElementReferencesTargets domain class Id.
		/// </summary>
		public static readonly new global::System.Guid DomainClassId = new global::System.Guid(0xa7cdcbb0, 0x161b, 0x4135, 0x9d, 0xbb, 0x5b, 0xbd, 0x4b, 0xbd, 0xe3, 0x7c);
	
				
		/// <summary>
		/// Constructor
		/// Creates a ExampleElementReferencesTargets link in the same Partition as the given ExampleElement
		/// </summary>
		/// <param name="source">ExampleElement to use as the source of the relationship.</param>
		/// <param name="target">ExampleElement to use as the target of the relationship.</param>
		public ExampleElementReferencesTargets(ExampleElement source, ExampleElement target)
			: base((source != null ? source.Partition : null), new DslModeling::RoleAssignment[]{new DslModeling::RoleAssignment(ExampleElementReferencesTargets.SourceDomainRoleId, source), new DslModeling::RoleAssignment(ExampleElementReferencesTargets.TargetDomainRoleId, target)}, null)
		{
		}
		
		/// <summary>
		/// Constructor
		/// </summary>
		/// <param name="store">Store where new link is to be created.</param>
		/// <param name="roleAssignments">List of relationship role assignments.</param>
		public ExampleElementReferencesTargets(DslModeling::Store store, params DslModeling::RoleAssignment[] roleAssignments)
			: base(store != null ? store.DefaultPartitionForClass(DomainClassId) : null, roleAssignments, null)
		{
		}
		
		/// <summary>
		/// Constructor
		/// </summary>
		/// <param name="store">Store where new link is to be created.</param>
		/// <param name="roleAssignments">List of relationship role assignments.</param>
		/// <param name="propertyAssignments">List of properties assignments to set on the new link.</param>
		public ExampleElementReferencesTargets(DslModeling::Store store, DslModeling::RoleAssignment[] roleAssignments, DslModeling::PropertyAssignment[] propertyAssignments)
			: base(store != null ? store.DefaultPartitionForClass(DomainClassId) : null, roleAssignments, propertyAssignments)
		{
		}
		
		/// <summary>
		/// Constructor
		/// </summary>
		/// <param name="partition">Partition where new link is to be created.</param>
		/// <param name="roleAssignments">List of relationship role assignments.</param>
		public ExampleElementReferencesTargets(DslModeling::Partition partition, params DslModeling::RoleAssignment[] roleAssignments)
			: base(partition, roleAssignments, null)
		{
		}
		
		/// <summary>
		/// Constructor
		/// </summary>
		/// <param name="partition">Partition where new link is to be created.</param>
		/// <param name="roleAssignments">List of relationship role assignments.</param>
		/// <param name="propertyAssignments">List of properties assignments to set on the new link.</param>
		public ExampleElementReferencesTargets(DslModeling::Partition partition, DslModeling::RoleAssignment[] roleAssignments, DslModeling::PropertyAssignment[] propertyAssignments)
			: base(partition, roleAssignments, propertyAssignments)
		{
		}
		#endregion
		#region Source domain role code
		
		/// <summary>
		/// Source domain role Id.
		/// </summary>
		public static readonly global::System.Guid SourceDomainRoleId = new global::System.Guid(0xc72ef35d, 0xcc8d, 0x4d74, 0xa2, 0x82, 0xcd, 0x01, 0x0f, 0x55, 0xc0, 0x02);
		
		/// <summary>
		/// DomainRole Source
		/// Description for imbNLP.PipelineDSLD.ExampleRelationship.Target
		/// </summary>
		[DslDesign::DisplayNameResource("imbNLP.PipelineDSLD.ExampleElementReferencesTargets/Source.DisplayName", typeof(global::imbNLP.PipelineDSLD.NLPPipelineDSLDDomainModel), "imbNLP.PipelineDSLD.GeneratedCode.DomainModelResx")]
		[DslDesign::DescriptionResource("imbNLP.PipelineDSLD.ExampleElementReferencesTargets/Source.Description", typeof(global::imbNLP.PipelineDSLD.NLPPipelineDSLDDomainModel), "imbNLP.PipelineDSLD.GeneratedCode.DomainModelResx")]
		[DslModeling::DomainRole(DslModeling::DomainRoleOrder.Source, PropertyName = "Targets", PropertyDisplayNameKey="imbNLP.PipelineDSLD.ExampleElementReferencesTargets/Source.PropertyDisplayName",  PropagatesCopy = DslModeling::PropagatesCopyOption.DoNotPropagateCopy, Multiplicity = DslModeling::Multiplicity.ZeroMany)]
		[DslModeling::DomainObjectId("c72ef35d-cc8d-4d74-a282-cd010f55c002")]
		public virtual ExampleElement Source
		{
			[global::System.Diagnostics.DebuggerStepThrough]
			get
			{
				return (ExampleElement)DslModeling::DomainRoleInfo.GetRolePlayer(this, SourceDomainRoleId);
			}
			[global::System.Diagnostics.DebuggerStepThrough]
			set
			{
				DslModeling::DomainRoleInfo.SetRolePlayer(this, SourceDomainRoleId, value);
			}
		}
				
		#endregion
		#region Static methods to access Sources of a ExampleElement
		/// <summary>
		/// Gets a list of Sources.
		/// </summary>
		[global::System.Diagnostics.DebuggerStepThrough]
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011")]
		public static DslModeling::LinkedElementCollection<ExampleElement> GetSources(ExampleElement element)
		{
			return GetRoleCollection<DslModeling::LinkedElementCollection<ExampleElement>, ExampleElement>(element, TargetDomainRoleId);
		}
		#endregion
		#region Target domain role code
		
		/// <summary>
		/// Target domain role Id.
		/// </summary>
		public static readonly global::System.Guid TargetDomainRoleId = new global::System.Guid(0x854f76f4, 0x3226, 0x42e8, 0x9f, 0x0c, 0x42, 0xba, 0x95, 0xeb, 0x0f, 0x59);
		
		/// <summary>
		/// DomainRole Target
		/// Description for imbNLP.PipelineDSLD.ExampleRelationship.Source
		/// </summary>
		[DslDesign::DisplayNameResource("imbNLP.PipelineDSLD.ExampleElementReferencesTargets/Target.DisplayName", typeof(global::imbNLP.PipelineDSLD.NLPPipelineDSLDDomainModel), "imbNLP.PipelineDSLD.GeneratedCode.DomainModelResx")]
		[DslDesign::DescriptionResource("imbNLP.PipelineDSLD.ExampleElementReferencesTargets/Target.Description", typeof(global::imbNLP.PipelineDSLD.NLPPipelineDSLDDomainModel), "imbNLP.PipelineDSLD.GeneratedCode.DomainModelResx")]
		[DslModeling::DomainRole(DslModeling::DomainRoleOrder.Target, PropertyName = "Sources", PropertyDisplayNameKey="imbNLP.PipelineDSLD.ExampleElementReferencesTargets/Target.PropertyDisplayName",  PropagatesCopy = DslModeling::PropagatesCopyOption.DoNotPropagateCopy, Multiplicity = DslModeling::Multiplicity.ZeroMany)]
		[DslModeling::DomainObjectId("854f76f4-3226-42e8-9f0c-42ba95eb0f59")]
		public virtual ExampleElement Target
		{
			[global::System.Diagnostics.DebuggerStepThrough]
			get
			{
				return (ExampleElement)DslModeling::DomainRoleInfo.GetRolePlayer(this, TargetDomainRoleId);
			}
			[global::System.Diagnostics.DebuggerStepThrough]
			set
			{
				DslModeling::DomainRoleInfo.SetRolePlayer(this, TargetDomainRoleId, value);
			}
		}
				
		#endregion
		#region Static methods to access Targets of a ExampleElement
		/// <summary>
		/// Gets a list of Targets.
		/// </summary>
		[global::System.Diagnostics.DebuggerStepThrough]
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011")]
		public static DslModeling::LinkedElementCollection<ExampleElement> GetTargets(ExampleElement element)
		{
			return GetRoleCollection<DslModeling::LinkedElementCollection<ExampleElement>, ExampleElement>(element, SourceDomainRoleId);
		}
		#endregion
		#region Source link accessor
		/// <summary>
		/// Get the list of ExampleElementReferencesTargets links to a ExampleElement.
		/// </summary>
		[global::System.Diagnostics.DebuggerStepThrough]
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011")]
		public static global::System.Collections.ObjectModel.ReadOnlyCollection<global::imbNLP.PipelineDSLD.ExampleElementReferencesTargets> GetLinksToTargets ( global::imbNLP.PipelineDSLD.ExampleElement sourceInstance )
		{
			return DslModeling::DomainRoleInfo.GetElementLinks<global::imbNLP.PipelineDSLD.ExampleElementReferencesTargets>(sourceInstance, global::imbNLP.PipelineDSLD.ExampleElementReferencesTargets.SourceDomainRoleId);
		}
		#endregion
		#region Target link accessor
		/// <summary>
		/// Get the list of ExampleElementReferencesTargets links to a ExampleElement.
		/// </summary>
		[global::System.Diagnostics.DebuggerStepThrough]
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011")]
		public static global::System.Collections.ObjectModel.ReadOnlyCollection<global::imbNLP.PipelineDSLD.ExampleElementReferencesTargets> GetLinksToSources ( global::imbNLP.PipelineDSLD.ExampleElement targetInstance )
		{
			return DslModeling::DomainRoleInfo.GetElementLinks<global::imbNLP.PipelineDSLD.ExampleElementReferencesTargets>(targetInstance, global::imbNLP.PipelineDSLD.ExampleElementReferencesTargets.TargetDomainRoleId);
		}
		#endregion
		#region ExampleElementReferencesTargets instance accessors
		
		/// <summary>
		/// Get any ExampleElementReferencesTargets links between a given ExampleElement and a ExampleElement.
		/// </summary>
		[global::System.Diagnostics.DebuggerStepThrough]
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011")]
		public static global::System.Collections.ObjectModel.ReadOnlyCollection<global::imbNLP.PipelineDSLD.ExampleElementReferencesTargets> GetLinks( global::imbNLP.PipelineDSLD.ExampleElement source, global::imbNLP.PipelineDSLD.ExampleElement target )
		{
			global::System.Collections.Generic.List<global::imbNLP.PipelineDSLD.ExampleElementReferencesTargets> outLinks = new global::System.Collections.Generic.List<global::imbNLP.PipelineDSLD.ExampleElementReferencesTargets>();
			global::System.Collections.Generic.IList<global::imbNLP.PipelineDSLD.ExampleElementReferencesTargets> links = DslModeling::DomainRoleInfo.GetElementLinks<global::imbNLP.PipelineDSLD.ExampleElementReferencesTargets>(source, global::imbNLP.PipelineDSLD.ExampleElementReferencesTargets.SourceDomainRoleId);
			foreach ( global::imbNLP.PipelineDSLD.ExampleElementReferencesTargets link in links )
			{
				if ( target.Equals(link.Target) )
				{
					outLinks.Add(link);
				}
			}
			return outLinks.AsReadOnly();
		}
		/// <summary>
		/// Get the one ExampleElementReferencesTargets link between a given ExampleElementand a ExampleElement.
		/// </summary>
		[global::System.Diagnostics.DebuggerStepThrough]
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011")]
		public static global::imbNLP.PipelineDSLD.ExampleElementReferencesTargets GetLink( global::imbNLP.PipelineDSLD.ExampleElement source, global::imbNLP.PipelineDSLD.ExampleElement target )
		{
			global::System.Collections.Generic.IList<global::imbNLP.PipelineDSLD.ExampleElementReferencesTargets> links = DslModeling::DomainRoleInfo.GetElementLinks<global::imbNLP.PipelineDSLD.ExampleElementReferencesTargets>(source, global::imbNLP.PipelineDSLD.ExampleElementReferencesTargets.SourceDomainRoleId);
			foreach ( global::imbNLP.PipelineDSLD.ExampleElementReferencesTargets link in links )
			{
				if ( target.Equals(link.Target) )
				{
					return link;
				}
			}
			return null;
		}
		
		#endregion
	}
}
